#!/usr/bin/python
import os

virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/'
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
os.environ['NLTK_DATA'] = "$OPENSHIFT_DATA_DIR/nltk"

nltkenv = os.environ['NLTK_DATA']
nltkenvi = os.path.join(nltkenv, 'bin/activate_this.py')

try:
    execfile(virtualenv, dict(__file__=virtualenv))
    execfile(nltkenvi, dict(__file__=nltkenvi))
except IOError:
    pass
#
# IMPORTANT: Put any additional includes below this line.  If placed above this
# line, it's possible required libraries won't be in your searchable path
# 

from app import app as application
